"""Repository protocol — the persistence seam (Req 11).

A local in-memory implementation is the default; an InsForge-backed adapter can
be swapped in behind the same interface via configuration.
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from ..models import Athlete, CheckIn, Streak


@runtime_checkable
class Repository(Protocol):
    # athletes
    def upsert_athlete(self, athlete: Athlete) -> Athlete: ...
    def get_athlete(self, athlete_id: str) -> Athlete | None: ...
    def list_athletes(self, coach_id: str | None = None) -> list[Athlete]: ...

    # check-ins
    def add_checkin(self, checkin: CheckIn) -> CheckIn: ...
    def get_latest_checkin(self, athlete_id: str) -> CheckIn | None: ...
    def get_checkins(self, athlete_id: str, days: int = 28) -> list[CheckIn]: ...
    def get_workload_history(self, athlete_id: str, days: int = 28) -> list[float]: ...

    # streaks
    def get_streak(self, athlete_id: str) -> Streak | None: ...
    def set_streak(self, streak: Streak) -> Streak: ...
